#!/bin/bash

#SBATCH --partition gpu_a100
#SBATCH --time=24:00:00
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=18
#SBATCH --gpus=1
#SBATCH --job-name=GNN_Train
#SBATCH --out=out/run.log
#SBATCH --err=out/run.log

source .venv/bin/activate

srun python main.py run $@