group: FirstGNNExperiment

parameters:
  seed: [42]

  training:
    batch_size: [8]
    epochs: [10, 20, 40]
    num_workers: [8]
    learning_rate: [0.01, 0.001, 0.0001]
    
  dataset:
    path: [Data/Water_Graph_dist.pt]

  model:
    name: [GNN]
    hidden_dim: [32, 64, 128]
    latent_dim: [32]
    depth: [1, 2, 4, 8]
    dropout: [0.3]

  loss:
    -
      name: [Focal]
      alpha: [0.25]
      gamma: [2.0]
    -
      name: BCEWithLogitsLoss

other_grids:
